# Dev-specific conf.
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tp_spring
    username: admin
    password: Ktoto1956
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create